
import 'package:flutter/material.dart';

class LanguageService {
  static ValueNotifier<String> languageNotifier =
      ValueNotifier<String>("en");

  static Map<String, Map<String, String>> texts = {
    "en": {
      "profile": "Profile",
      "editProfile": "Edit Profile",
      "payment": "Payment Methods",
      "notifications": "Notifications",
      "language": "Language",
      "help": "Help Center",
      "logout": "Log Out",
      "recycled": "Recycled",
      "pickups": "Pickups",
      "level": "Level 4 Recycler",
      "totalRecycled": "Total Recycled",
      "ecoCoins": "EcoCoins",
      "keepRecycling": "Keep recycling to level up!",
      "account": "Account",
      "privacySecurity": "Privacy & Security",
      "appSettings": "App Settings",
      "darkMode": "Dark Mode",
      "deleteAccount": "Delete Account",
      "confirmLogout": "Are you sure you want to log out?",
      "cancel": "Cancel",
      "deleteWarning": "This action cannot be undone. All your data will be permanently deleted.",
      "saveChanges": "Save Changes",
      "fullName": "Full Name",
      "phoneNumber": "Phone Number",
      "address": "Address",
      "city": "City",
      "optional": "Optional",
      "pickImage": "Pick Image from Gallery",
      "profileUpdated": "Profile updated successfully!",
      "errorUpdating": "Error updating profile",
      "enterName": "Please enter your name",
      "notificationTypes": "Notification Types",
      "pickupReminders": "Pickup Reminders",
      "pickupRemindersDesc": "Reminders for scheduled pickups",
      "ecoCoinUpdates": "EcoCoin Updates",
      "ecoCoinUpdatesDesc": "When you earn or spend EcoCoins",
      "promotions": "Promotions & Offers",
      "promotionsDesc": "Special deals and discounts",
      "newsletter": "Newsletter",
      "newsletterDesc": "Weekly recycling tips and news",
      "notificationPrefs": "Notification Preferences",
      "sound": "Sound",
      "soundDesc": "Play sound for notifications",
      "vibration": "Vibration",
      "vibrationDesc": "Vibrate for notifications",
      "dailyDigest": "Daily Digest Time",
      "dailyDigestDesc": "Receive daily summary at",
      "testNotification": "Test Notification",
      "testNotificationDesc": "Send a test notification to check your settings",
      "sendTest": "Send Test Notification",
      "testSent": "Test notification sent!",
      "recentNotifications": "Recent Notifications",
      "pickupScheduled": "Pickup Scheduled",
      "pickupScheduledDesc": "Your pickup is scheduled for tomorrow at 10:00 AM",
      "ecoCoinsEarned": "EcoCoins Earned",
      "ecoCoinsEarnedDesc": "You earned 50 EcoCoins for recycling plastic bottles",
      "rewardAvailable": "Reward Available",
      "rewardAvailableDesc": "New reward available: Eco-straw Set for 1250 coins",
      "today": "Today, 09:00",
      "yesterday": "Yesterday, 14:30",
      "jan12": "Jan 12, 11:15",
      "clearAll": "Clear All Notifications",
      "saveSettings": "Save Settings",
      "settingsSaved": "Notification settings saved successfully",
      "resetSettings": "Reset to Default Settings",
      "resetConfirm": "Are you sure you want to reset all notification settings to default?",
      "reset": "Reset",
      "settingsReset": "Settings reset to default",
      "other": "Other",
      "notificationSettings": "Notification Settings",
      "notificationSettingsDesc": "Customize how and when you receive notifications from RecycleX",
    },
    "am": {
      "profile": "መገለጫ",
      "editProfile": "መገለጫ አርትዕ",
      "payment": "የክፍያ ዘዴዎች",
      "notifications": "ማሳወቂያዎች",
      "language": "ቋንቋ",
      "help": "የእገዛ ማዕከል",
      "logout": "ውጣ",
      "recycled": "የተመለሰ",
      "pickups": "መሰብሰቦች",
      "level": "ደረጃ 4 መለስ",
      "totalRecycled": "ጠቅላላ የተመለሰ",
      "ecoCoins": "ኢኮኮይንስ",
      "keepRecycling": "ለማሻሻል መለስ!",
      "account": "መለያ",
      "privacySecurity": "ግላዊነት እና ደህንነት",
      "appSettings": "የመተግበሪያ ቅንብሮች",
      "darkMode": "ጨለማ ሁነታ",
      "deleteAccount": "መለያ ሰርዝ",
      "confirmLogout": "እርግጠኛ ነህ መውጣት ትፈልጋለህ?",
      "cancel": "ሰርዝ",
      "deleteWarning": "ይህ ተግባር ሊቀለበስ አይችልም። ሁሉም ውሂብዎ ለዘላለም ይሰረዛል።",
      "saveChanges": "ለውጦችን አስቀምጥ",
      "fullName": "ሙሉ ስም",
      "phoneNumber": "ስልክ ቁጥር",
      "address": "አድራሻ",
      "city": "ከተማ",
      "optional": "አማራጭ",
      "pickImage": "ከጋላሪ ምስል ምረጥ",
      "profileUpdated": "መገለጫው በተሳካ ሁኔታ ተዘምኗል!",
      "errorUpdating": "መገለጫ በማዘመን ላይ ስህተት",
      "enterName": "እባክዎ ስምዎን ያስገቡ",
      "notificationTypes": "የማሳወቂያ አይነቶች",
      "pickupReminders": "የመሰብሰብ አስታውሻዎች",
      "pickupRemindersDesc": "ለተዘጋጁ መሰብሰቦች አስታውሻዎች",
      "ecoCoinUpdates": "ኢኮኮይን ዝማኔዎች",
      "ecoCoinUpdatesDesc": "ኢኮኮይን በሚያገኙበት ወይም በሚያወጡበት ጊዜ",
      "promotions": "ማስተዋወቂያዎች እና ቅናሾች",
      "promotionsDesc": "ልዩ ቅናሾች እና ቅናሾች",
      "newsletter": "የወር አበባ ዜና",
      "newsletterDesc": "የሳምንት መልሶ መጠቀም ምክሮች እና ዜና",
      "notificationPrefs": "የማሳወቂያ ምርጫዎች",
      "sound": "ድምፅ",
      "soundDesc": "ለማሳወቂያዎች ድምፅ ማጫወት",
      "vibration": "ብርጭቆ",
      "vibrationDesc": "ለማሳወቂያዎች መብረቆል",
      "dailyDigest": "ዕለታዊ ማጠቃለያ ጊዜ",
      "dailyDigestDesc": "ዕለታዊ ማጠቃለያ በ",
      "testNotification": "ሙከራ ማሳወቂያ",
      "testNotificationDesc": "የእርስዎን ቅንብሮች ለመፈተሽ ሙከራ ማሳወቂያ ይላኩ",
      "sendTest": "ሙከራ ማሳወቂያ ይላኩ",
      "testSent": "ሙከራ ማሳወቂያ ተልኳል!",
      "recentNotifications": "የቅርብ ጊዜ ማሳወቂያዎች",
      "pickupScheduled": "መሰብሰብ ተዘጋጅቷል",
      "pickupScheduledDesc": "መሰብሰብዎ ነገ በጠዋት 10፡00 ላይ ተዘጋጅቷል",
      "ecoCoinsEarned": "ኢኮኮይን ተገኝቷል",
      "ecoCoinsEarnedDesc": "የፕላስቲክ ጠርሙሶችን በመለስዎ 50 ኢኮኮይን አገኙ",
      "rewardAvailable": "ሽልማት ዝግጁ ነው",
      "rewardAvailableDesc": "አዲስ ሽልማት ዝግጁ ነው፡ የኢኮ-ስትሮ ስብስብ በ1250 ኮይኖች",
      "today": "ዛሬ፣ 09፡00",
      "yesterday": "ትላንት፣ 14፡30",
      "jan12": "ጃን 12፣ 11፡15",
      "clearAll": "ሁሉንም ማሳወቂያዎች አጽዳ",
      "saveSettings": "ቅንብሮችን አስቀምጥ",
      "settingsSaved": "የማሳወቂያ ቅንብሮች በተሳካ ሁኔታ ተቀምጠዋል",
      "resetSettings": "ወደ ነባሪ ቅንብሮች መልስ",
      "resetConfirm": "ሁሉንም የማሳወቂያ ቅንብሮች ወደ ነባሪ መመለስ ትፈልጋለህ?",
      "reset": "እንደገና አስጀምር",
      "settingsReset": "ቅንብሮች ወደ ነባሪ ተመልሰዋል",
      "other": "ሌላ",
      "notificationSettings": "የማሳወቂያ ቅንብሮች",
      "notificationSettingsDesc": "ከ RecycleX ማሳወቂያዎችን እንዴት እና መቼ እንደሚቀበሉ ያብጁ",
    },
  };

  static String t(String key) {
    return texts[languageNotifier.value]?[key] ?? key;
  }

  static void toggleLanguage() {
    languageNotifier.value =
        languageNotifier.value == "en" ? "am" : "en";
  }
}
